global:
  external_labels:
    "server": "prom-1"
    "site": "prod"
  scrape_interval: 5s

# Rules and alerts are read from the specified file(s)
rule_files:
  - prom-alert-rules.yml


# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - alertmanager:9093



scrape_configs:
  - job_name: prometheus-1
    scrape_interval: 5s
    honor_labels: true    
    static_configs:
      - targets:
          - 'prometheus-1:9090'
    metrics_path: /metrics
  - job_name: prometheus-2
    scrape_interval: 5s
    honor_labels: true    
    static_configs:
      - targets:
          - 'prometheus-2:9090'
    metrics_path: /metrics

  - job_name: nginx-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'nginx-exporter:9113'
    metrics_path: /metrics
  
  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'node-exporter:9100'
    metrics_path: /metrics
  
  - job_name: wordpress-exporter
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: 
        - '192.168.254.37:9112'
  
  - job_name: blackbox-http
    honor_timestamps: true
    params:
      module:
        - http_2xx
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: __param_target
        replacement: $1
        action: replace
      - source_labels: [__param_target]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: blackbox-exporter:9115
        action: replace
    static_configs:
      - targets:
          - https://otus.ru
          - http://webserver
  
  - job_name: fpm-exporter
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'fpm-exporter:9253'
    metrics_path: /metrics

  - job_name: 'thanos'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'thanos-sidecar-1:10902'
          - 'thanos-sidecar-2:10902'
          - 'thanos-querier:10902'
