global:
  telegram_api_url: https://api.telegram.org
  smtp_smarthost: 'smtp.yandex.ru:587'
  smtp_from: 'cherepnin_pk@ooovsa.ru'
  smtp_auth_username: 'cherepnin_pk@ooovsa.ru'
  smtp_auth_password: 'mmtbuurfwcqkvpqg'

# templates:

route:
  receiver: 'telegram'

  # group_by: ['alertname', 'cluster']

  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3m

  routes:
  - match:
      severity: warning
    receiver: 'telegram'

  - match:
      severity: critical
    receiver: 'mail'

receivers:
- name: 'mail'
  email_configs:
  - to: paul.cherepnin@gmail.com
    send_resolved: true
    require_tls: true
    tls_config:
      insecure_skip_verify: true


- name: 'telegram'
  telegram_configs:
  - bot_token: 6373314630:AAE1Bu3j4XlXQG_Dl5ZEoXneBpNwGXLB084
    chat_id: 800512876
    send_resolved: true
    parse_mode: HTML
  